### ISSUE TITLE
使用Reader 替代 filename 更通用，兼容读内存不读文件

### ISSUE THREAD

**Issue by horllion** [cuishu/excel#1]
type Sheet struct {
	reader   io.Reader
	Sheet    string
	filter   Schema
}

func (s Sheet) Scan(v interface{}) error {
	rv := reflect.ValueOf(v)
	if rv.Kind() != reflect.Ptr || rv.IsNil() || rv.Type().Elem().Kind() != reflect.Slice {
		panic("param must be slice pointer")
	}
	f, err := excelize.OpenReader(s.reader)
	if err != nil {
		return err
	}
	return s.scanSheet(f, rv)
}

**Comment by cuishu** [comment]
我稍后会添加这个功能,

**Comment by cuishu** [comment]
已经支持从io.Reader读取了
